version: 0.1

phases:
  build:
    commands:
      - echo Building project on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - commons.jar
  discard-paths: yes