version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Building project on `date`
      - export JAVA_HOME="$JAVA_11_HOME"
      - export JRE_HOME="$JRE_11_HOME"
      - export JDK_HOME="$JDK_11_HOME"
      - java -version
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'